url: "http://jessbird.me"
baseurl: ""

# Site settings
title: Jess Bird
description: "Portfolio"

# Contact
email: jessannbird@gmail.com
github: https://github.com/jestann
linkedin: https://linkedin.com/in/jessannbird
stack-overflow: https://stackoverflow.com/users/6890046/jess-b

# Fix this section to match contact and footer.
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, twitter, etc.)
social:
  - title: github
    url: https://github.com/jestann
  - title: linkedin
    url: https://linkedin.com/in/jessannbird
  - title: stack-overflow
    url: https://stackoverflow.com/users/6890046/jess-b

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed
collections:
  portfolio:
    output: true
  pages:
    output: true

# Pagination
# plugins: [jekyll-paginate]
# paginate: 3
# paginate_path: "posts/page:num"
# str_next: ">>"
# str_prev: "<<"

# katex: true # Enable if using math markup